[workspace]
members = [
  "eurochef/cli",
  "eurochef/gui",
  "eurochef/shared",
  "eurochef-edb",
  "eurochef-elx",
  "eurochef-filelist"
]

[profile.dev.package.image]
opt-level = 3

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2 # fast and small wasm
lto = true