[package]
name = "eurochef"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "cli"

# [[bin]]
# name = "edbtool"
# path = 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive", "color"] }
clap-num = "1"
eurochef-edb = { path = "../eurochef-edb" }
eurochef-elx = { path = "../eurochef-elx" }
eurochef-filelist = { path = "../eurochef-filelist" }
pathdiff = "0.2.1"
image = "0.24"
squish = "1.0"
walkdir = "2.3"
indicatif = "0.17.3"
enumn = "0.1"
